module VerbalizeIt
  module Language
    # Supported languages. You can also get this list via languages api.
    LANGUAGES = {
      "afr-ZA" => "Afrikaans",
      "ara-AE" => "Arabic",
      "bos-BA" => "Bosnian",
      "bul-BG" => "Bulgarian",
      "cat-ES" => "Catalan",
      "ces-CZ" => "Czech",
      "cmn-CN" => "Mandarin",
      "dan-DK" => "Danish",
      "deu-CH" => "German (Switzerland)",
      "deu-DE" => "German",
      "dut-NL" => "Dutch",
      "ell-GR" => "Greek",
      "eng-AU" => "English (Australia)",
      "eng-CA" => "English (Canada)",
      "eng-GB" => "English (UK)",
      "eng-US" => "English",
      "est-EE" => "Estonian",
      "fas-IR" => "Farsi",
      "fin-FI" => "Finnish",
      "fra-CA" => "French (Canada)",
      "fra-FR" => "French",
      "heb-IL" => "Hebrew",
      "hin-IN" => "Hindi",
      "hrv-HR" => "Croatian",
      "hun-HU" => "Hungarian",
      "ind-ID" => "Indonesian",
      "ita-IT" => "Italian",
      "jpn-JP" => "Japanese",
      "kan-IN" => "Kannada",
      "kaz-KZ" => "Kazakh",
      "kor-KR" => "Korean",
      "lav-LV" => "Latvian",
      "lit-LT" => "Lithuanian",
      "nno-NO" => "Nynorsk",
      "nob-NO" => "Bokmål",
      "nor-NO" => "Norwegian",
      "pan-IN" => "Punjabi",
      "pol-PL" => "Polish",
      "por-BR" => "Portuguese (Brazil)",
      "por-PT" => "Portuguese",
      "prs-AF" => "Dari",
      "pus-AF" => "Pashto",
      "ron-RO" => "Romanian",
      "rus-RU" => "Russian",
      "slo-SK" => "Slovak",
      "slv-SI" => "Slovenian",
      "spa-ES" => "Spanish",
      "spa-MX" => "Spanish (Mexico)",
      "spa-XL" => "Spanish (Latin America)",
      "srp-SP" => "Serbian",
      "swa-KE" => "Swahili",
      "swe-SE" => "Swedish",
      "tam-IN" => "Tamil",
      "tgl-PH" => "Tagalog",
      "tha-TH" => "Thai",
      "tur-TR" => "Turkish",
      "ukr-UA" => "Ukrainian",
      "vie-VN" => "Vietnamese",
      "zho-CN" => "Traditional Chinese",
      "zho-HK" => "Traditional Chinese (Hong Kong)",
      "zho-TW" => "Traditional Chinese (Taiwan)"
    }
  end
end
